owner: plusoon
repo: status
user-agent: plusoon
sites:
  - name: plusoon.com
    url: https://plusoon.com
  - name: blog.plusoon.com
    url: https://blog.plusoon.com
  - name: blog-api.p1ass.com
    url: https://blog-api.p1ass.com/rss
  - name: midare.p1ass.com
    url: https://midare.p1ass.com
  - name: midare-api.p1ass.com
    url: https://midare-api.p1ass.com
  - name: grafana.p1ass.com
    url: https://grafana.p1ass.com/
  # - name: Secret Site
  # url: $SECRET_SITE
notifications:
  - type: slack
    channel: C01DD5Y3H17
assignees:
  - p1ass
status-website:
  cname: status.plusoon.com
  logoUrl: https://raw.githubusercontent.com/plusoon/status/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: plusoon status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "*.plusoon.comを外形監視しています。"
  apiBaseUrl: https://api.github.com
