owner: p1ass
repo: status
user-agent: p1ass
sites:
  - name: p1ass.com
    url: https://p1ass.com
  - name: blog.p1ass.com
    url: https://blog.p1ass.com
  - name: blog-api.p1ass.com
    url: https://blog-api.p1ass.com/rss
  - name: midare.p1ass.com
    url: https://midare.p1ass.com
  - name: midare-api.p1ass.com
    url: https://midare-api.p1ass.com
  # - name: Secret Site
  # url: $SECRET_SITE
notifications:
  - type: slack
    channel: C01DD5Y3H17
assignees:
  - p1ass
status-website:
  cname: status.p1ass.com
  logoUrl: https://raw.githubusercontent.com/p1ass/status/79d9d1c22ecf706acc51f17798d7c7dbc710ab40/assets/icon.svg
  name: p1ass status
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: "*.p1ass.comを外形監視しています。"
  apiBaseUrl: https://api.github.com
